version: '3'

services:
  puppet:
    container_name: puppetserver
    hostname: puppetserver
    image: puppet/puppetserver-standalone
    ports:
      - 8140:8140
    volumes:
      - ./code:/etc/puppetlabs/code/
      #- ./ssl:/etc/puppetlabs/puppet/ssl/